project:
  type: book
  output-dir: _book

book:
  title: "R Programlama"
  subtitle: "Veri Analizi ve İstatistiksel Düşünmeye Uygulamalı Giriş"
  author: 
    name: "Muhammed Fatih Tüzen"
    url: https://www.linkedin.com/in/dr-m-fatih-t-2b2a4328/
  reader-mode: true
  page-navigation: true
  search: true
  sharing: [twitter, linkedin]
  page-footer:
    left: |
      &copy; 2026, [Muhammed Fatih Tüzen](https://www.linkedin.com/in/dr-m-fatih-t-2b2a4328/)
    right: |
      Bu kitap [Quarto](https://quarto.org/) ile hazırlanmıştır.
  cover-image: images/cover.png
  site-url: https://mfatihtuzen.github.io/r-programlama/
  repo-url: https://github.com/MFatihTuzen/r-programlama
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - r_about.qmd
    - R_intro.qmd
    # - part: R_intro.qmd
    #   chapters: 
    #     - basics.qmd
    #     - data_types.qmd
    #     - functions.qmd
    #     - if_else_for.qmd
    #     - date_time.qmd
    #     - strings.qmd
    #     - apply.qmd
    #     - import_export.qmd
    # - data_manipulation.qmd
    # - data_transformation.qmd
    # - data_join.qmd
    # - data_analysis.qmd
    # - ggplot2.qmd
    # - data_preprocess.qmd
    # - statistics.qmd
    # - regresyon.qmd

language: 
  title-block-author-single: "Yazar"
  toc-title-document: "İçindekiler"

format:
  html:
    toc: true
    toc-depth: 4
    toc-expand: 2
    theme: 
      light: sandstone
      dark: cyborg
    css: styles.css
    code-copy: true
    code-overflow: wrap
    code-link: true
    anchor-sections: true
    smooth-scroll: true
    grid:
      sidebar-width: 280px
      body-width: 820px
      margin-width: 260px
      gutter-width: 1.5rem
  # pdf:
  #   documentclass: scrreprt
  #   pdf-engine: xelatex
  #   keep-tex: true

editor: visual
